
export const settings_default_light = {
   buttonBackground: 'linear-gradient(to top left, #a8c7d8, #b4d4e8)',
   buttonColor: '#09182a',
   brightColor: '#b3d1e3',
   cloneeditColor: '#d6efffff',
   cloneFontSize: 18,
   cloneTitleBackground: 'linear-gradient(to right, #94aeb5ff, #6ba2c6ff)',
   darkColor: '#1d1a22',
   editorBackground: 'linear-gradient(to top, #5f7481ff, #55697eff)',
   editorFont: 'Funnel Sans',
   editorColor: '#d6efffff',
   editorFontSize: 24,
   effectEditorBackground: 'linear-gradient(to top, #6e7678ff, #647171ff)',
   effectEditorColor: '#f4d39eff',
   effectEditorFontSize: 16,
   inputBackground: '#d4d8d1ff',
   lightDarkColor: '#68879bff',
   material: 'linear-gradient(to right, #5d7c8fff, #6ba2c6ff)',
   materialMedian: '#638da8',
   mezzoDarkColor: '#252935',
   selectedColor: '#d6efffff',
   width: 800,
}